### ISSUE TITLE
Deprecate `--dependency-check-properties` command line option

### ISSUE THREAD

**Issue by lread** [clj-holmes/clj-watson#107]
From https://github.com/clj-holmes/clj-watson/pull/106#issuecomment-2297338429

## Currently
The `--dependency-check-properties` is more confusing than helpful, and is superseded by `--clj-watson-properties`.

## So
Let's go ahead and deprecate it.

### Option 1: Do nothing - continue to support.
Con: The option is confusing
Con: we have to maintain and make sure it works

### Option 2: Turf it, breaking change. 
This seems ok to me.
Con: breaks usage for x number of users. Maybe x = 0?
Pro: simplifies our life.

### Option 3: Stop documenting the feature and warn if it is used. 
Usage and README would not describe the feature and warn that it is slated for deletion if used.
Pro: gives users time to adapt.
Con: It is a burden on us to test/support for a bit longer.

## Decision
@seancorfield has chosen option 3 for now. 
A future release will likely implement option 2.

## Next Steps
I can follow up with PR if that would help you.

**Comment by seancorfield** [comment]
Yes, PR please -- it'll give me more insight into the CLI lib...

**Comment by lread** [comment]
I like babashka.cli because it is helpful but not rigid.
