### ISSUE TITLE
Can't run clj-watson as a -M alias

### ISSUE THREAD

**Issue by danjelalura** [clj-holmes/clj-watson#28]
Hello, 
First of all, thank you for the work you are doing with clj-watson! :) 

I am receiving the following error when I run clj-watson as a -M alias: 

`Execution error - invalid arguments to cli-matic.utils-v2/cfg-v2 at (test.cljc:30).
nil - failed: some? at: [:cfg :v1 :commands :opts :default] spec: :cli-matic.specs/default
nil - failed: string? at: [:cfg :v1 :app :version] spec: :cli-matic.specs/existing-string`

Running the command below fires the same error:
`clojure -M:clj-watson scan -\?`

There seems to be an issue with parsing of command line arguments and I wanted to ask if you are able to reproduce it? 

Thank you!

**Comment by mthbernardes** [comment]
Hi @danjelalura,
Thx, it's really good to know that people are using it 😄 also feel free to contribute to the project I'm looking for people to help maintain it.
Do you have cli-matic as a dependency in our `deps.edn`? You add the clj-watson alias to your `deps.edn` right?

**Comment by danjelalura** [comment]
Hi @mthbernardes , 
Sorry for the late reply! It seems like the issue is not happening anymore with the new version of clj-watson.
