### ISSUE TITLE
Bug in 4.1.1?

### ISSUE THREAD

**Issue by seancorfield** [clj-holmes/clj-watson#30]
I updated to 4.1.1 and tried to scan our repo and got this error:

```
...
Downloading: cli-matic/cli-matic/0.5.4/cli-matic-0.5.4.jar from clojars
Execution error (FileNotFoundException) at clj-watson.adapter.config/eval220$loading (config.clj:1).
Could not locate clj_time/format__init.class, clj_time/format.clj or clj_time/format.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

I reverted to 4.1.0 and the scan works fine.

**Comment by hukka** [comment]
I suppose https://github.com/clj-holmes/clj-watson/commit/efa3420025d2392d351b5a0c4bed665d627a6c38 removed the dependency to clj-time, which is still required in config.clj.

**Comment by mthbernardes** [comment]
🚧 working on it.

**Comment by mthbernardes** [comment]
New release with the missing dependency
https://github.com/clj-holmes/clj-watson/releases/tag/v4.1.2

**Comment by seancorfield** [comment]
Thank you! Works perfectly now!
