### ISSUE TITLE
Compare/contrast with nvd-clojure in README?

### ISSUE THREAD

**Issue by seancorfield** [clj-holmes/clj-watson#5]
I wonder if you could add a section to the README outlining the pros of cons of clj-watson vs https://github.com/rm-hull/nvd-clojure (another Dependency-Check wrapper that has been around for a while)?

I'd be interested to know why/if we should switch from nvd-clojure at work to clj-watson.

**Comment by mthbernardes** [comment]
Hey @seancorfield here are  nvd-clojure gives the package name and CVEs. clj-watson produce more information regarding the vulnerable package like the dependency tree, the cvss of each vulnerability and the most important a suggested fix to each vulnerability.

**Comment by seancorfield** [comment]
Sounds like good information for your README, so others don't have to ask the same question.

Your README doesn't explain how to install clj-watson. Can it be used via git deps and `-X` or `-T`?

**Comment by seancorfield** [comment]
I tried a few invocations that failed with mysterious exceptions and reverted to `-M -m` which "worked" but produced no output:

```bash
(! 645)-> clojure -Sdeps '{:deps {io.github.clj-holmes/clj-watson {:git/sha "a1b37f23b04e8b95313a1ba6bfe4f0379607da3b"}}}' -M -m clj-watson.cli scan -p deps.edn
Downloading/Updating database.
Download/Update completed.
```

Since nvd-clojure finds CVEs in some of our dependencies, I'm guessing clj-watson doesn't check what dependencies are in aliases (and there's no way to tell it what aliases should be in effect)?

I'll take this to Slack and see if we can hammer it out interactively. I'm not sure whether our use case (monorepo, Polylith style) is supported by clj-watson and I can't tell from your README what is actually supposed to work.
