### ISSUE TITLE
You probably need to bump dependency-check

### ISSUE THREAD

**Issue by lread** [clj-holmes/clj-watson#60]
Just a heads up, I can't imagine that https://github.com/rm-hull/nvd-clojure/issues/178 is not affecting clj-watson too.

**Comment by carrete** [comment]
clj-watson did not work for me until I updated to 10.0.2 or 10.0.3, FYI

**Comment by seancorfield** [comment]
FWIW, I always specify `org.owasp/dependency-check-core {:mvn/version "RELEASE"}` as a dependency alongside `clj-watson` but, yes, it would be nice to have that updated.

**Comment by seancorfield** [comment]
Fixed in #61 but you'll need to use the full SHA for a git dependency until I get around to updating the CHANGELOG for 5.1.2 (ahem) and the changes since then...
