### ISSUE TITLE
dev: Consider adding a handful of babashka tasks

### ISSUE THREAD

**Issue by lread** [clj-holmes/clj-watson#82]
On many projects, I've employed [babashka tasks](https://book.babashka.org/#tasks) as quick directory of dev-related things I can do.
They also quickly tell the story of what a dev _should_ do as well!

For this project we might start with:

- `dev` to bring up an nREPL
- `test` to run tests
- `lint` (currently carried out by clojure-lsp, which is kind of interesting!) 
- `security` to run clj-holmes checks 
- `outdated` to list outdated deps

If there are no strong objections I would like to proceed with this.

**Comment by seancorfield** [comment]
My only objection to this is that it forces contributing devs to install Babashka and it adds an overhead to CI.

**Comment by lread** [comment]
Thanks @seancorfield, I'm personally OK with those cons. 
CI overhead would be relatively minimal. Delaguardo setup-clojure already supports installing babashka.
True, some devs might not have babashka installed, but I expect that number is becoming fewer and fewer.

Since you are the primary maintainer, it is up to you, but I feel a directory of easy-to-discover and run tasks really helps.

**Comment by seancorfield** [comment]
I don't use Babashka -- I think it's use is much less widespread than you think. I had this discussion at work, BTW, when I suggested bringing in `bb` and was talked out of it. We do everything via `build.clj` -- `clojure -T:deps:build help/doc` lists all the public functions with their docstrings.

I'd be fine with adding a `build.clj` file for automated tasks -- most of my OSS projects do this.

**Comment by lread** [comment]
> I had this discussion at work, BTW, when I suggested bringing in `bb` and was talked out of it.

You lost the battle there, but can so easily win the battle here! :slightly_smiling_face:

**Comment by lread** [comment]
Ok, I'm getting the hint that I won't win you over on this one, @seancorfield, at least not today! :slightly_smiling_face: 

If someday you become interested in exploring babashka tasks and babashka, I'm happy to contribute.

Feel free to close this one.
