### ISSUE TITLE
chore: clj-time is deprecated

### ISSUE THREAD

**Issue by lread** [clj-holmes/clj-watson#83]
Clj-watson is using [clj-time](https://github.com/clj-time/clj-time), which has been deprecated.

Consider replacing.

**Comment by lread** [comment]
@seancorfield do you have a preferred time lib? Or do you prefer Java interop? 
It does not look like clj-watson is doing anything terribly fancy or complex.

**Comment by seancorfield** [comment]
Plain Java interop ought to be fine. At work we replaced `clj-time` usage with Java Time interop (although we went via `clojure.java-time` in some places, but we've weaned ourselves off that too now).
