### ISSUE TITLE
Consider clearly reporting the number of findings

### ISSUE THREAD

**Issue by lread** [clj-holmes/clj-watson#87]
## Currently
When there are no vulnerabilities found, I don't see a clear indication of such.

This leaves me wondering if the scan actually worked.

I suppose using the `--fail-on-result` option gives some indication that nothing was found, but I don't think this is enough.

## Proposal
Emit the number of findings after the vulnerability report.
Something like:

```
Total vulnerabilities detected: 0
```

**Comment by lread** [comment]
It might also be nice to include the number of items scanned if that makes sense:

```
Total items scanned: 42
Total vulnerabilities detected: 7
```
Should look into appropriate nouns while doing the work and tweak messages appropriately.

**Comment by lread** [comment]
Ok, I'm thinking as the final summary:

```
Dependencies Scanned: 151
Vulnerable Dependencies Found: 7 (4 Critical, 1 High, 2 Medium)
```

Or if all good:
```
Dependencies Scanned: 151
Vulnerable Dependencies Found: 0
```

Severities can be [Critical, High, Medium, Low](https://nvd.nist.gov/vuln-metrics/cvss).
Might be worth color coding as well.

I like this summary, but I also quite like nvd-clojure's summary and might include something inspired by it above the final summary.

![image](https://github.com/user-attachments/assets/ae655a56-155b-4e13-a3d4-4db633c03de7)

**Comment by lread** [comment]
I'm also taking some inspiration from [trivy](https://github.com/aquasecurity/trivy):

![image](https://github.com/user-attachments/assets/06fc944d-4327-4933-b0e9-244f62b236cb)

**Comment by seancorfield** [comment]
This will be optional, triggered by a new command-line arg? 🙂

**Comment by lread** [comment]
I like that trivy does not solely rely on colors to convey severity. The counts columns are interesting too.

Here are some sample summaries (I use screenshots to share colored text).
These would appear after the report (which might put some more weight on us dealing with structured report output #98)

## Scanning clj-watson itself
We'll fix these up, but for now they are useful for my mockup!:
```
clojure -M:clj-watson scan -p deps.edn
```
![image](https://github.com/user-attachments/assets/e3481afa-d781-4ba1-92bd-0f0a5a48e9da)

## Scanning vulnerable-deps.edn
Clj-watson includes and handy sample dep with lots of vulnerabilities:
```
clojure -M:clj-watson scan -p resources/vulnerable-deps.edn
```
![image](https://github.com/user-attachments/assets/5bbfdcc5-977c-4cf0-91fb-c8759d67f698)

## Scanning when no vulnerabilities
Here's me scanning cljdoc:

```
Dependencies Scanned: 211
Vulnerable Dependencies Found: 0
```

**Comment by lread** [comment]
I think I'll split the summary table into a separate issue.

The scope of this issue will be the two final summary lines, examples:

```
Dependencies Scanned: 211
Vulnerable Dependencies Found: 0
```

```
Dependencies Scanned: 60
Vulnerable Dependencies Found: 7 (2 Critical, 3 High, 2 Medium)
```

**Comment by seancorfield** [comment]
Sounds good. Happy for both to go in 6.1 but, as I said, I don't think the full colored table output should be the default: users should be able to opt into that via a command-line option.

**Comment by lread** [comment]
Ah... Ok, I get it now, I saw this as a question and not a strong hint!:

> This will be optional, triggered by a new command-line arg? 🙂

I've listed some options in #113.
